### ISSUE TITLE
Client crash at login when username of jid is empty

### ISSUE THREAD

**Issue by ruthger** [ArchipelProject/Archipel#1112]
When retype the username at the login screen and you make clear the username part of the jid, the client crashes. If you selected the Remember switch the login crash goes in to a loop.
I had to clear the local storage to get out of the loop

**Comment by ruthger** [comment]
user-agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36Exception: TNStropheJIDExceptionJID: @archipel.guppycloud.com is not a valid JIDVersion: 0.6.0-f876a58 (Apophis)Stack Trace:  TNStropheJIDExceptionJID: @archipel.guppycloud.com is not a valid JID,    at $CPException__alloc (eval at <anonymous> (https://archipel.guppycloud.com/Frameworks/Objective-J/Objective-J.js:8141:16), <anonymous>:51:18),    at objj_msgSendFast0 [as objj_msgSend0] (https://archipel.guppycloud.com/Frameworks/Objective-J/Objective-J.js:8846:8),    at $CPException__exceptionWithName_reason_userInfo_ (eval at <anonymous> (https://archipel.guppycloud.com/Frameworks/Objective-J/Objective-J.js:8141:16), <anonymous>:70:31),    at objj_msgSendFast3 [as objj_msgSend3] (https://archipel.guppycloud.com/Frameworks/Objective-J/Objective-J.js:8870:8),    at $CPException__raise_reason_ (eval at <anonymous> (https://archipel.guppycloud.com/Frameworks/Objective-J/Objective-J.js:8141:16), <anonymous>:57:24),    at objj_msgSend (https://archipel.guppycloud.com/Frameworks/Objective-J/Objective-J.js:8822:8),    at $TNStropheJID__initWithString_ (eval at <anonymous> (https://archipel.guppycloud.com/Frameworks/Objective-J/Objective-J.js:8141:16), <anonymous>:95:89),    at objj_msgSend (https://archipel.guppycloud.com/Frameworks/Objective-J/Objective-J.js:8820:8),    at catcher_objj_msgSend (eval at <anonymous> (https://archipel.guppycloud.com/Frameworks/Objective-J/Objective-J.js:8141:16), <anonymous>:285:29),    at $TNStropheJID__stropheJIDWithString_ (eval at <anonymous> (https://archipel.guppycloud.com/Frameworks/Objective-J/Objective-J.js:8141:16), <anonymous>:180:38)
