### ISSUE TITLE
Agent startup error

### ISSUE THREAD

**Issue by RomanBogachev** [ArchipelProject/Archipel#1130]
If
```sh
[root@test-1~]# service archipel start
 * Starting Archipel: [OK]
```

```sh
[root@test-1 ~]# runarchipel
[root@test-1 ~]# Traceback (most recent call last):
  File "/usr/bin/runarchipel", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/opt/ArchipelAgent/archipel-agent/install/bin/runarchipel", line 175, in <module>
    main(config)
  File "/opt/ArchipelAgent/archipel-agent/install/bin/runarchipel", line 86, in main
    hypervisor = TNArchipelHypervisor(jid, password, config, name, database)
  File "/opt/ArchipelAgent/archipel-agent/archipel/archipelHypervisor.py", line 137, in __init__
    TNArchipelEntity.__init__(self, jid, password, configuration, name)
  File "/opt/ArchipelAgent/archipel-core/archipelcore/archipelEntity.py", line 162, in __init__
    self.ipaddr = socket.gethostbyname(socket.gethostname())
socket.gaierror: [Errno -3] Temporary failure in name resolution
```

What's the problem?

**Comment by CyrilPeponnet** [comment]
Your host definition is bad. 

Check your host file or DNS resolution from this host.

**Comment by RomanBogachev** [comment]
All success. 

```sh
# TEST 1 : XMPP CONNECTION
 * Trying to connect to the XMPP Server using admin@mydomain.com
   [SUCCESS] : Sucessfully connected

# TEST 2 : INBAND REGISTRATION
 * Trying to register a new dummy XMPP account using in-band registration
 * Registration information sent. Wait for response...
   [SUCCESS] : Registration complete.

# TEST 3 : PUBSUB CREATION
 * Trying to create a pubsub node with the dummy account
   [SUCCESS] : Dummy pubsub created.

# TEST 4 : PUBSUB CONFIGURATION
 * Trying to configure the pubsub with required info for Archipel...
   [SUCCESS] : Pubsub sucessfully configured with correct value

# TEST 5 : PUBSUB DELETION
 * Trying to remove dummy pubsub...
   [SUCCESS] : Sucessfully deleted the pubsub.

# TEST 6 : INBAND UNREGISTRATION
 * Trying to unregister the dummy XMPP account using in-band unregistration
 * Unregistration information sent. Waiting for response...
   [SUCCESS] : Unregistration complete.

# TEST 7 : QUICK REGISTRATION/UNREGISTRATION
 * Trying to register a new dummy XMPP account using in-band registration
 * Registration information sent. Wait for response...
   [SUCCESS] : Registration complete.
 * Trying to unregister the dummy XMPP account using in-band unregistration
 * Unregistration information sent. Waiting for response...
   [SUCCESS] : Unregistration complete.

# TEST 8 : EJABBERD_XMLRPC BASIC OPERATION
 * Trying to connect the ejabberd_xmlrpc module...
   [SUCCESS] : Successfully contacted ejabberd_xmlrpc module

# TEST 9 : CHECKING FOR MOD_ADMIN_EXTRA
 * Checking is mod_admin_extra is available...
   [SUCCESS] : Successfully contacted mod_admin_extra over ejabberd_xmlrpc module

# TEST 10 : CHECKING FOR USER MANAGEMENT THROUGH XMPP API
 * Trying to list registered users using XMPP admin commands (XEP-133)
 * Command sent. Wait for response...
   [SUCCESS] : User Management is enabled

your XMPP server should be ready!
```

Servers available for each other via hostname.
But XMPP server doesnt initialize agent, and `runarchipel` starts with error.

**Comment by CyrilPeponnet** [comment]
Not related. 

It's your hypervisors hostname resolution which fails. 

Either fix it or set the ip on the conf file instead of auto.
