### ISSUE TITLE
TNArchipelHypervisor.loop

### ISSUE THREAD

**Issue by RomanBogachev** [ArchipelProject/Archipel#1132]
```sh
ERROR   ::2015-04-18 18:40:32::utils.py:76::TNArchipelHypervisor.loop (test-1@mysite.com/test-1)::LOOP EXCEPTION : Disconnected from server. Trying to reconnect in 5 seconds.
ERROR   ::2015-04-18 18:40:32::utils.py:76::TNArchipelHypervisor.loop (test-1@mysite.com/test-1)::TRACEBACK: Traceback (most recent call last):

  File "/opt/ArchipelAgent/archipel-core/archipelcore/archipelEntity.py", line 1253, in loop
    self.xmppclient.disconnect()

  File "/opt/ArchipelAgent/archipel-core/archipelcore/xmpp/dispatcher.py", line 377, in disconnect
    self._owner_send('</stream:stream>')

  File "/opt/ArchipelAgent/archipel-core/archipelcore/xmpp/transports.py", line 251, in send
    self._owner.disconnected()

  File "/opt/ArchipelAgent/archipel-core/archipelcore/xmpp/client.py", line 129, in disconnected
    for i in self.disconnect_handlers: i()

  File "/opt/ArchipelAgent/archipel-core/archipelcore/xmpp/client.py", line 137, in DisconnectHandler
    raise IOError('Disconnected from server.')

IOError: Disconnected from server.
```

Reconnect every 5 seconds with "Replaced by new connection"

**Comment by CyrilPeponnet** [comment]
Two Archipel process running at the same time.
