### ISSUE TITLE
Unable to build StropheCappuccino

### ISSUE THREAD

**Issue by YATV** [ArchipelProject/Archipel#1172]
* VNCCappuccino build
 * Building StropheCappuccino
(in /usr/Archipel/ArchipelClient/Libraries/StropheCappuccino)
(in /usr/Archipel/ArchipelClient/Libraries/StropheCappuccino)
make strophe.js
make[1]: Entering directory `/usr/Archipel/ArchipelClient/Libraries/StropheCappuccino/strophejs'
make stamp-bower
make[2]: Entering directory `/usr/Archipel/ArchipelClient/Libraries/StropheCappuccino/strophejs'
node_modules/.bin/bower install
? May bower anonymously report usage statistics to improve the tool over time? (Y/n) bower qunit#~1.16.0         not-cached git://github.com/jquery/qunit.git#~1.16.0
bower qunit#~1.16.0            resolve git://github.com/jquery/qunit.git#~1.16.0
bower sinon#*                   cached http://sinonjs.org/releases/sinon-1.12.2.js#e-tag:562fe09b-
bower sinon#*                 validate e-tag:562fe09b- against http://sinonjs.org/releases/sinon-1.12.2.js#*
bower sinon-qunit#~2.0.0        cached git://github.com/cjohansen/sinon-qunit.git#2.0.0
bower sinon-qunit#~2.0.0      validate 2.0.0 against git://github.com/cjohansen/sinon-qunit.git#~2.0.0
bower jquery#1.11.0             cached git://github.com/jquery/jquery.git#1.11.0
bower jquery#1.11.0           validate 1.11.0 against git://github.com/jquery/jquery.git#1.11.0
bower requirejs#~2.1.15         cached git://github.com/jrburke/requirejs-bower.git#2.1.22
bower requirejs#~2.1.15       validate 2.1.22 against git://github.com/jrburke/requirejs-bower.git#~2.1.15
bower almond#~0.3.0             cached git://github.com/jrburke/almond.git#0.3.1
bower almond#~0.3.0           validate 0.3.1 against git://github.com/jrburke/almond.git#~0.3.0
bower qunit#~1.16.0           download https://github.com/jquery/qunit/archive/1.16.0.tar.gz
bower qunit#~1.16.0            extract archive.tar.gz
bower qunit#~1.16.0           resolved git://github.com/jquery/qunit.git#1.16.0
bower                           EACCES EACCES, mkdir '/usr/Archipel/ArchipelClient/Libraries/StropheCappuccino/strophejs/bower_components'

Stack trace:
Error: EACCES, mkdir '/usr/Archipel/ArchipelClient/Libraries/StropheCappuccino/strophejs/bower_components'

Console trace:
Error
    at StandardRenderer.error (/usr/Archipel/ArchipelClient/Libraries/StropheCappuccino/strophejs/node_modules/bower/lib/renderers/StandardRenderer.js:82:37)
    at Logger.<anonymous> (/usr/Archipel/ArchipelClient/Libraries/StropheCappuccino/strophejs/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/usr/Archipel/ArchipelClient/Libraries/StropheCappuccino/strophejs/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/Archipel/ArchipelClient/Libraries/StropheCappuccino/strophejs/node_modules/bower/lib/commands/index.js:48:20
    at _rejected (/usr/Archipel/ArchipelClient/Libraries/StropheCappuccino/strophejs/node_modules/bower/node_modules/q/q.js:844:24)
    at /usr/Archipel/ArchipelClient/Libraries/StropheCappuccino/strophejs/node_modules/bower/node_modules/q/q.js:870:30
    at Promise.when (/usr/Archipel/ArchipelClient/Libraries/StropheCappuccino/strophejs/node_modules/bower/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/Archipel/ArchipelClient/Libraries/StropheCappuccino/strophejs/node_modules/bower/node_modules/q/q.js:788:41)
    at /usr/Archipel/ArchipelClient/Libraries/StropheCappuccino/strophejs/node_modules/bower/node_modules/q/q.js:604:44
System info:
Bower version: 1.6.8
Node version: 0.10.36
OS: Linux 3.10.0-229.14.1.el7.x86_64 x64
make[2]: *** [stamp-bower] Error 1
make[2]: Leaving directory `/usr/Archipel/ArchipelClient/Libraries/StropheCappuccino/strophejs'
make[1]: *** [strophe.js] Error 2
make[1]: Leaving directory `/usr/Archipel/ArchipelClient/Libraries/StropheCappuccino/strophejs'
make: *** [strophe.min.js] Error 2
Unable to build StropheCappuccino

**Comment by YATV** [comment]
$ mkdir /usr/Archipel/ArchipelClient/Libraries/StropheCappuccino/strophejs/bower_components
mkdir: cannot create directory ‘/usr/Archipel/ArchipelClient/Libraries/StropheCappuccino/strophejs/bower_components’: Permission denied

**Comment by YATV** [comment]
$ sudo mkdir /usr/Archipel/ArchipelClient/Libraries/StropheCappuccino/strophejs/bower_components
[sudo] password for YaTv:
$ sudo chown YaTv:root /usr/Archipel/ArchipelClient/Libraries/StropheCappuccino/strophejs/bower_components/

**Comment by YATV** [comment]
This is resolved problem:

    $ sudo chown -R YaTv:root /usr/Archipel/ArchipelClient/
