### ISSUE TITLE
Disconnected from server

### ISSUE THREAD

**Issue by YATV** [ArchipelProject/Archipel#1185]
Archipel version 0.6.0-af2266d (Apophis)

![image](https://cloud.githubusercontent.com/assets/2369847/16755310/9c0a966c-47d1-11e6-9321-35a46d0eab97.png)

WARNING ::2016-07-12 07:29:07.808::utils.py:75::TNArchipelCentralAgent.handle_autogroup_for_entities (centralagent@mgmt.mydomain.net/mgmt.mydomain.net)::XMPPSERVER: unable to add entity c70b00d2-ba63-11e5-9ee3-001cc441924c@mgmt.mydomain.net in autogroup All Virtual Machines: EOF occurred in violation of protocol (_ssl.c:765)
WARNING ::2016-07-12 07:29:07.827::utils.py:75::TNArchipelCentralAgent.handle_autogroup_for_entities (centralagent@mgmt.mydomain.net/mgmt.mydomain.net)::XMPPSERVER: unable to add entity 82f7c32a-91b7-11e3-980e-001cc441924c@mgmt.mydomain.net in autogroup All Virtual Machines: EOF occurred in violation of protocol (_ssl.c:765)
WARNING ::2016-07-12 07:29:07.846::utils.py:75::TNArchipelCentralAgent.handle_autogroup_for_entities (centralagent@mgmt.mydomain.net/mgmt.mydomain.net)::XMPPSERVER: unable to add entity 16daea18-6454-11e3-b43c-001cc441924c@mgmt.mydomain.net in autogroup All Virtual Machines: EOF occurred in violation of protocol (_ssl.c:765)
WARNING ::2016-07-12 07:29:07.862::utils.py:75::TNArchipelCentralAgent.handle_autogroup_for_entities (centralagent@mgmt.mydomain.net/mgmt.mydomain.net)::XMPPSERVER: unable to add entity b1f189a8-25ff-11e5-a9b3-001cc441924c@mgmt.mydomain.net in autogroup All Virtual Machines: EOF occurred in violation of protocol (_ssl.c:765)
WARNING ::2016-07-12 07:29:07.878::utils.py:75::TNArchipelCentralAgent.handle_autogroup_for_entities (centralagent@mgmt.mydomain.net/mgmt.mydomain.net)::XMPPSERVER: unable to add entity 1206792c-9315-11e3-980e-001cc441924c@mgmt.mydomain.net in autogroup All Virtual Machines: EOF occurred in violation of protocol (_ssl.c:765)
WARNING ::2016-07-12 07:29:07.894::utils.py:75::TNArchipelCentralAgent.handle_autogroup_for_entities (centralagent@mgmt.mydomain.net/mgmt.mydomain.net)::XMPPSERVER: unable to add entity 06ad6340-baf7-11e5-9ee3-001cc441924c@mgmt.mydomain.net in autogroup All Virtual Machines: EOF occurred in violation of protocol (_ssl.c:765)
WARNING ::2016-07-12 07:29:07.911::utils.py:75::TNArchipelCentralAgent.handle_autogroup_for_entities (centralagent@mgmt.mydomain.net/mgmt.mydomain.net)::XMPPSERVER: unable to add entity 48f1d65c-9305-11e4-9b50-001cc441924c@mgmt.mydomain.net in autogroup All Virtual Machines: EOF occurred in violation of protocol (_ssl.c:765)
WARNING ::2016-07-12 07:29:07.927::utils.py:75::TNArchipelCentralAgent.handle_autogroup_for_entities (centralagent@mgmt.mydomain.net/mgmt.mydomain.net)::XMPPSERVER: unable to add entity 937bc61a-8db6-11e3-b260-001cc441924c@mgmt.mydomain.net in autogroup All Virtual Machines: EOF occurred in violation of protocol (_ssl.c:765)
WARNING ::2016-07-12 07:29:07.956::utils.py:75::TNArchipelCentralAgent.handle_autogroup_for_entities (centralagent@mgmt.mydomain.net/mgmt.mydomain.net)::XMPPSERVER: unable to add entity 1-srv-h.mgmt.mydomain.net@mgmt.mydomain.net/mgmt.mydomain.net in autogroup All Hypervisors: EOF occurred in violation of protocol (_ssl.c:765)
WARNING ::2016-07-12 07:29:07.987::utils.py:75::TNArchipelCentralAgent.handle_autogroup_for_entities (centralagent@mgmt.mydomain.net/mgmt.mydomain.net)::XMPPSERVER: unable to add entity dbab93ac-8e83-11e3-980e-001cc441924c@mgmt.mydomain.net in autogroup All Virtual Machines: EOF occurred in violation of protocol (_ssl.c:765)
ERROR   ::2016-07-12 07:30:44.832::utils.py:77::TNArchipelCentralAgent.loop (centralagent@mgmt.mydomain.net/mgmt.mydomain.net)::LOOP EXCEPTION : Disconnected from server. Trying to reconnect in 5 seconds.
ERROR   ::2016-07-12 07:30:44.833::utils.py:77::TNArchipelCentralAgent.loop (centralagent@mgmt.mydomain.net/mgmt.mydomain.net)::TRACEBACK: Traceback (most recent call last):

  File "/usr/Archipel/ArchipelAgent/archipel-core/archipelcore/archipelEntity.py", line 1252, in loop
    self.xmppclient.Process(3)

  File "/usr/Archipel/ArchipelAgent/archipel-core/archipelcore/xmpp/dispatcher.py", line 123, in Process
    self.Stream.Parse(data)

  File "/usr/Archipel/ArchipelAgent/archipel-core/archipelcore/xmpp/simplexml.py", line 425, in endtag
    self.dispatch(self._mini_dom)

  File "/usr/Archipel/ArchipelAgent/archipel-core/archipelcore/xmpp/dispatcher.py", line 295, in dispatch
    try: cb(session,stanza,**args)

  File "/usr/Archipel/ArchipelAgent/archipel-agent-xmppserver/archipelagentxmppserver/xmppserver.py", line 310, in on_receive_users_num
    answer = self._send_xmlrpc_call("registered_users", {"host": xmppserver})

  File "/usr/Archipel/ArchipelAgent/archipel-agent-xmppserver/archipelagentxmppserver/xmppserver.py", line 276, in _send_xmlrpc_call
    raise Exception(str(ex).replace(self.xmlrpc_password, "[PASSWORD_HIDDEN]"))

Exception: EOF occurred in violation of protocol (_ssl.c:765)

ERROR   ::2016-07-12 07:30:49.840::utils.py:77::TNArchipelCentralAgent.loop (centralagent@mgmt.mydomain.net/mgmt.mydomain.net)::LOOP EXCEPTION : Disconnected from server. Trying to reconnect in 5 seconds.
ERROR   ::2016-07-12 07:30:49.842::utils.py:77::TNArchipelCentralAgent.loop (centralagent@mgmt.mydomain.net/mgmt.mydomain.net)::TRACEBACK: Traceback (most recent call last):

  File "/usr/Archipel/ArchipelAgent/archipel-core/archipelcore/archipelEntity.py", line 1255, in loop
    self.xmppclient.disconnect()

  File "/usr/Archipel/ArchipelAgent/archipel-core/archipelcore/xmpp/dispatcher.py", line 378, in disconnect
    while self.Process(1): pass

  File "/usr/Archipel/ArchipelAgent/archipel-core/archipelcore/xmpp/dispatcher.py", line 123, in Process
    self.Stream.Parse(data)

ExpatError: parsing finished: line 1, column 210269

ERROR   ::2016-07-12 07:30:54.847::utils.py:77::TNArchipelCentralAgent.loop (centralagent@mgmt.mydomain.net/mgmt.mydomain.net)::LOOP EXCEPTION : Disconnected from server. Trying to reconnect in 5 seconds.
ERROR   ::2016-07-12 07:30:54.849::utils.py:77::TNArchipelCentralAgent.loop (centralagent@mgmt.mydomain.net/mgmt.mydomain.net)::TRACEBACK: Traceback (most recent call last):

  File "/usr/Archipel/ArchipelAgent/archipel-core/archipelcore/archipelEntity.py", line 1255, in loop
    self.xmppclient.disconnect()

  File "/usr/Archipel/ArchipelAgent/archipel-core/archipelcore/xmpp/dispatcher.py", line 378, in disconnect
    while self.Process(1): pass

  File "/usr/Archipel/ArchipelAgent/archipel-core/archipelcore/xmpp/dispatcher.py", line 123, in Process
    self.Stream.Parse(data)

ExpatError: parsing finished: line 1, column 210269

ERROR   ::2016-07-12 07:30:59.857::utils.py:77::TNArchipelCentralAgent.loop (centralagent@mgmt.mydomain.net/mgmt.mydomain.net)::LOOP EXCEPTION : Disconnected from server. Trying to reconnect in 5 seconds.
ERROR   ::2016-07-12 07:30:59.871::utils.py:77::TNArchipelCentralAgent.loop (centralagent@mgmt.mydomain.net/mgmt.mydomain.net)::TRACEBACK: Traceback (most recent call last):

  File "/usr/Archipel/ArchipelAgent/archipel-core/archipelcore/archipelEntity.py", line 1255, in loop
    self.xmppclient.disconnect()

  File "/usr/Archipel/ArchipelAgent/archipel-core/archipelcore/xmpp/dispatcher.py", line 377, in disconnect
    self._owner_send('</stream:stream>')

  File "/usr/Archipel/ArchipelAgent/archipel-core/archipelcore/xmpp/transports.py", line 251, in send
    self._owner.disconnected()

  File "/usr/Archipel/ArchipelAgent/archipel-core/archipelcore/xmpp/client.py", line 129, in disconnected
    for i in self.disconnect_handlers: i()

  File "/usr/Archipel/ArchipelAgent/archipel-core/archipelcore/xmpp/client.py", line 137, in DisconnectHandler
    raise IOError('Disconnected from server.')

IOError: Disconnected from server.

ERROR   ::2016-07-12 07:31:05.976::utils.py:77::TNArchipelCentralAgent.create_autogroups_if_needed (centralagent@mgmt.mydomain.net/mgmt.mydomain.net)::XMPPSERVER: Unable to use xmlrpc. EOF occurred in violation of protocol (_ssl.c:765)
ERROR   ::2016-07-12 07:31:06.362::utils.py:77::TNArchipelCentralAgent.loop (centralagent@mgmt.mydomain.net/mgmt.mydomain.net)::LOOP EXCEPTION : Disconnected from server. Trying to reconnect in 5 seconds.
ERROR   ::2016-07-12 07:31:06.363::utils.py:77::TNArchipelCentralAgent.loop (centralagent@mgmt.mydomain.net/mgmt.mydomain.net)::TRACEBACK: Traceback (most recent call last):

  File "/usr/Archipel/ArchipelAgent/archipel-core/archipelcore/archipelEntity.py", line 1252, in loop
    self.xmppclient.Process(3)

  File "/usr/Archipel/ArchipelAgent/archipel-core/archipelcore/xmpp/dispatcher.py", line 123, in Process
    self.Stream.Parse(data)

  File "/usr/Archipel/ArchipelAgent/archipel-core/archipelcore/xmpp/simplexml.py", line 425, in endtag
    self.dispatch(self._mini_dom)

  File "/usr/Archipel/ArchipelAgent/archipel-core/archipelcore/xmpp/dispatcher.py", line 295, in dispatch
    try: cb(session,stanza,**args)

  File "/usr/Archipel/ArchipelAgent/archipel-agent-xmppserver/archipelagentxmppserver/xmppserver.py", line 310, in on_receive_users_num
    answer = self._send_xmlrpc_call("registered_users", {"host": xmppserver})

  File "/usr/Archipel/ArchipelAgent/archipel-agent-xmppserver/archipelagentxmppserver/xmppserver.py", line 276, in _send_xmlrpc_call
    raise Exception(str(ex).replace(self.xmlrpc_password, "[PASSWORD_HIDDEN]"))

Exception: EOF occurred in violation of protocol (_ssl.c:765)

ERROR   ::2016-07-12 07:31:11.371::utils.py:77::TNArchipelCentralAgent.loop (centralagent@mgmt.mydomain.net/mgmt.mydomain.net)::LOOP EXCEPTION : Disconnected from server. Trying to reconnect in 5 seconds.
ERROR   ::2016-07-12 07:31:11.373::utils.py:77::TNArchipelCentralAgent.loop (centralagent@mgmt.mydomain.net/mgmt.mydomain.net)::TRACEBACK: Traceback (most recent call last):

  File "/usr/Archipel/ArchipelAgent/archipel-core/archipelcore/archipelEntity.py", line 1255, in loop
    self.xmppclient.disconnect()

  File "/usr/Archipel/ArchipelAgent/archipel-core/archipelcore/xmpp/dispatcher.py", line 378, in disconnect
    while self.Process(1): pass

  File "/usr/Archipel/ArchipelAgent/archipel-core/archipelcore/xmpp/dispatcher.py", line 123, in Process
    self.Stream.Parse(data)

ExpatError: parsing finished: line 1, column 26070

ERROR   ::2016-07-12 07:31:16.376::utils.py:77::TNArchipelCentralAgent.loop (centralagent@mgmt.mydomain.net/mgmt.mydomain.net)::LOOP EXCEPTION : Disconnected from server. Trying to reconnect in 5 seconds.
ERROR   ::2016-07-12 07:31:16.378::utils.py:77::TNArchipelCentralAgent.loop (centralagent@mgmt.mydomain.net/mgmt.mydomain.net)::TRACEBACK: Traceback (most recent call last):

  File "/usr/Archipel/ArchipelAgent/archipel-core/archipelcore/archipelEntity.py", line 1255, in loop
    self.xmppclient.disconnect()

  File "/usr/Archipel/ArchipelAgent/archipel-core/archipelcore/xmpp/dispatcher.py", line 378, in disconnect
    while self.Process(1): pass

  File "/usr/Archipel/ArchipelAgent/archipel-core/archipelcore/xmpp/dispatcher.py", line 123, in Process
    self.Stream.Parse(data)

ExpatError: parsing finished: line 1, column 26070

ERROR   ::2016-07-12 07:31:21.384::utils.py:77::TNArchipelCentralAgent.loop (centralagent@mgmt.mydomain.net/mgmt.mydomain.net)::LOOP EXCEPTION : Disconnected from server. Trying to reconnect in 5 seconds.
ERROR   ::2016-07-12 07:31:21.385::utils.py:77::TNArchipelCentralAgent.loop (centralagent@mgmt.mydomain.net/mgmt.mydomain.net)::TRACEBACK: Traceback (most recent call last):

  File "/usr/Archipel/ArchipelAgent/archipel-core/archipelcore/archipelEntity.py", line 1255, in loop
    self.xmppclient.disconnect()

  File "/usr/Archipel/ArchipelAgent/archipel-core/archipelcore/xmpp/dispatcher.py", line 377, in disconnect
    self._owner_send('</stream:stream>')

  File "/usr/Archipel/ArchipelAgent/archipel-core/archipelcore/xmpp/transports.py", line 251, in send
    self._owner.disconnected()

  File "/usr/Archipel/ArchipelAgent/archipel-core/archipelcore/xmpp/client.py", line 129, in disconnected
    for i in self.disconnect_handlers: i()

  File "/usr/Archipel/ArchipelAgent/archipel-core/archipelcore/xmpp/client.py", line 137, in DisconnectHandler
    raise IOError('Disconnected from server.')

IOError: Disconnected from server.

**Comment by YATV** [comment]
# ejabberdctl status
The node 'ejabberd@mgmt.mydomain.net' is started with status: started
ejabberd 16.06 is running in that node

**Comment by YATV** [comment]
# archipel-testxmppserver -j login -p password
*******************************************************************************
*                        Archipel XMPP Server Test                            *
*                                                                             *
* Archipel needs some specific parameters to be set. This tool will perform   *
* some tests in order to ensure that your ejabberd server is properly         *
* configured.                                                                 *
* If you encounter some errors during test, there are great chance that       *
* Archipel won't work correctly. If so, please read carrefully :              *
*                                                                             *
* - https://github.com/ArchipelProject/Archipel/wiki/Installation-manual      *
*                                                                             *
* Copyright 2011 Antoine Mercadal                                             *
*******************************************************************************

Type enter key to continue...

# TEST 1 : XMPP CONNECTION
 * Trying to connect to the XMPP Server using admin@mgmt.mydomain.net
   [SUCCESS] : Sucessfully connected

# TEST 2 : INBAND REGISTRATION
 * Trying to register a new dummy XMPP account using in-band registration
 * Registration information sent. Wait for response...
   [SUCCESS] : Registration complete.

# TEST 3 : PUBSUB CREATION
 * Trying to create a pubsub node with the dummy account
   [SUCCESS] : Dummy pubsub created.

# TEST 4 : PUBSUB CONFIGURATION
 * Trying to configure the pubsub with required info for Archipel...
   [SUCCESS] : Pubsub sucessfully configured with correct value

# TEST 5 : PUBSUB DELETION
 * Trying to remove dummy pubsub...
   [SUCCESS] : Sucessfully deleted the pubsub.

# TEST 6 : INBAND UNREGISTRATION
 * Trying to unregister the dummy XMPP account using in-band unregistration
 * Unregistration information sent. Waiting for response...
   [SUCCESS] : Unregistration complete.

# TEST 7 : QUICK REGISTRATION/UNREGISTRATION
 * Trying to register a new dummy XMPP account using in-band registration
 * Registration information sent. Wait for response...
   [SUCCESS] : Registration complete.
 * Trying to unregister the dummy XMPP account using in-band unregistration
 * Unregistration information sent. Waiting for response...
   [SUCCESS] : Unregistration complete.

# TEST 8 : EJABBERD_XMLRPC BASIC OPERATION
 * Trying to connect the ejabberd_xmlrpc module...
   [SUCCESS] : Successfully contacted ejabberd_xmlrpc module

# TEST 9 : CHECKING FOR MOD_ADMIN_EXTRA
 * Checking is mod_admin_extra is available...
   [SUCCESS] : Successfully contacted mod_admin_extra over ejabberd_xmlrpc module

# TEST 10 : CHECKING FOR USER MANAGEMENT THROUGH XMPP API
 * Trying to list registered users using XMPP admin commands (XEP-133)
 * Command sent. Wait for response...
   [SUCCESS] : User Management is enabled

your XMPP server should be ready!

**Comment by YATV** [comment]
How to fix disconnect and loop ?
