### ISSUE TITLE
Jake build procedure is outdated

### ISSUE THREAD

**Issue by perry-mitchell** [ArchipelProject/Archipel#1198]
The Jake file references the "system" module, for example, which is not a built-in in Node:

```
var SYSTEM = require("system");
```

The build process should be updated for current node versions 6/7 or a reasonable LTS build. I am unable to build the client due to errors surrounding running this:

```
jake aborted.
Error: Cannot find module 'system'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
```

I get no response on the IRC and the mailing list looks dormant.

**Comment by YATV** [comment]
yum install npm
npm install system
