### ISSUE TITLE
Error: Cannot find module 'narwhal/util'

### ISSUE THREAD

**Issue by YATV** [ArchipelProject/Archipel#1200]
# ./bootstrap
	###############################################################################
	#                                                                             #
	#                            Archipel Client                                  #
	#                                                                             #
	###############################################################################

	Welcome to the installation script of Archipel Client.
	Note that you must be root in order to install this software. Please answer the
	following questions.

	 * Do want to start installation ? [y/n] :
	###############################################################################
	#                                                                             #
	#                            Archipel Client                                  #
	#                                                                             #
	###############################################################################

	Welcome to the installation script of Archipel Client.
	Note that you must be root in order to install this software. Please answer the
	following questions.

	 Testing environment

	 * Would you like to build Cappuccino ? [y/n] : y
	 * Would you like to build GrowlCappuccino ? [y/n] : y
	 * Would you like to build VNCCappuccino ? [y/n] : y
	 * Would you like to build StropheCappuccino ? [y/n] : y
	 * Would you like to build TNKit ? [y/n] : y
	 * Would you like to build LPKit ? [y/n] : y
	 * Would you like to build Archipel Client ? [y/n] : y
	 * Would you like to apply Cappuccino Framework ? [y/n] : y
	 * Would you like to export Archipel ? [y/n] : y
	 * Where do you want to export Archipel Client ? [~/] : y

	 Installation information
	   - build Cappuccino            : True
	   - build GrowlCappuccino       : True
	   - build VNCCappuccino         : True
	   - build StropheCappuccino     : True
	   - build TNKit                 : True
	   - build LPKit                 : True
	   - build Archipel Client       : True
	   - apply Cappuccino            : True
	   - export to                   : y

	 * Do you confirm ? [y/n] : y
	 * Building Cappuccino

	*******************************************************************************
	Error: Narwhal is not compatible with your version of OpenJDK: OpenJDK Runtime Environment (build 1.8.0_91-b14).
	Please upgrade to OpenJDK >= 6b18 or switch to the Sun JVM. Then re-run bootstrap.sh.

					   _______ ____  ___  __ __________(_)__  ___
					  / __/ _ `/ _ \/ _ \/ // / __/ __/ / _ \/ _ \
					  \__/\_,_/ .__/ .__/\_,_/\__/\__/_/_//_/\___/
							 /_/  /_/

								 Welcome to Cappuccino!

	================================================================================

									 Version v0.9.8

							 http://cappuccino-project.org
						http://github.com/cappuccino/cappuccino
						   irc://irc.freenode.org#cappuccino

	This script will install the Cappuccino environment for you. Continue?
	Enter "yes" or "no":
	no
	jake aborted.
	Error: Cannot find module 'narwhal/util'
		at Function.Module._resolveFilename (module.js:338:15)
		at Function.Module._load (module.js:280:25)
	(See full trace by running task with --trace)
	*******************************************************************************
	Unable to build Cappuccino
	

	# npm install narwhal/util
	npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:narwhal/util.git /root/.npm/_git-remotes/git-github-com-narwhal-util-git-199fc2c2: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-narwhal-util-git-199fc2c2'...
	npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:narwhal/util.git /root/.npm/_git-remotes/git-github-com-narwhal-util-git-199fc2c2:
	npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:narwhal/util.git /root/.npm/_git-remotes/git-github-com-narwhal-util-git-199fc2c2: Permission denied (publickey).
	npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:narwhal/util.git /root/.npm/_git-remotes/git-github-com-narwhal-util-git-199fc2c2: fatal: Could not read from remote repository.
	npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:narwhal/util.git /root/.npm/_git-remotes/git-github-com-narwhal-util-git-199fc2c2:
	npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:narwhal/util.git /root/.npm/_git-remotes/git-github-com-narwhal-util-git-199fc2c2: Please make sure you have the correct access rights
	npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:narwhal/util.git /root/.npm/_git-remotes/git-github-com-narwhal-util-git-199fc2c2: and the repository exists.
	npm ERR! Linux 3.10.0-514.6.2.el7.x86_64
	npm ERR! argv "/usr/bin/node" "/bin/npm" "install" "narwhal/util"
	npm ERR! node v6.9.4
	npm ERR! npm  v3.10.10
	npm ERR! code 128

	npm ERR! Command failed: git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:narwhal/util.git /root/.npm/_git-remotes/git-github-com-narwhal-util-git-199fc2c2
	npm ERR! Permission denied (publickey).
	npm ERR! fatal: Could not read from remote repository.
	npm ERR!
	npm ERR! Please make sure you have the correct access rights
	npm ERR! and the repository exists.
	npm ERR!
	npm ERR!
	npm ERR! If you need help, you may report this error at:
	npm ERR!     <https://github.com/npm/npm/issues>

	npm ERR! Please include the following file with any support request:
	npm ERR!     /usr/Archipel/npm-debug.log

**Comment by HTPC-Schrauber** [comment]
Can you try in two steps.

In first run only set build Cappuccino to yes, the rest to no.
In the second run set build Cappuccino to no, the rest to yes.
