### ISSUE TITLE
Hypervisor shows as offline, please help

### ISSUE THREAD

**Issue by zietbukuel** [ArchipelProject/Archipel#805]
Hello, my hypervisor is shown as offline in the Archipel GUI, however, using ejabberd connected_users (or using the webadmin) it shows that it IS online.

I'm using:

Ubuntu 12.04.2 LTS
Latest nightly builds for the Agent and Client.
Ejabberd 2.1.10-2ubuntu1.1

My hostname is set to lowercase, I use the fqdn. I did not create the Hypervisor user manually, I let Archipel do it for me.

The Archipel logs shows this:

```
ERROR   ::2013-07-02 06:55:14::utils.py:75::TNArchipelHypervisor.loop (domain.com@domain.com/domain.com)::LOOP EXCEPTION : Disconnected from server. Trying to reconnect in 5 seconds.
ERROR   ::2013-07-02 06:55:14::utils.py:75::TNArchipelHypervisor.loop (domain.com@domain.com/domain.com)::TRACEBACK: Traceback (most recent call last):

  File "/usr/local/ArchipelAgent/archipel-core/archipelcore/archipelEntity.py", line 1256, in loop
    self.on_xmpp_loop_tick()

  File "/usr/local/ArchipelAgent/archipel-agent/archipel/archipelHypervisor.py", line 1338, in on_xmpp_loop_tick
    if self.wait_for_central_agent:

AttributeError: 'TNArchipelHypervisor' object has no attribute 'wait_for_central_agent'
```

Then I noticed that after a while, Ejabberd seems to die or something and when I try to execute ejabberd connected_users I get:

```
{error_logger,{{2013,7,2},{6,58,32}},"Protocol: ~p: register error: ~p~n",["inet_tcp",{{badmatch,{error,duplicate_name}},[{inet_tcp_dist,listen,1},{net_kernel,start_protos,4},{net_kernel,start_protos,3},{net_kernel,init_node,2},{net_kernel,init,1},{gen_server,init_it,6},{proc_lib,init_p_do_apply,3}]}]}
{error_logger,{{2013,7,2},{6,58,32}},crash_report,[[{initial_call,{net_kernel,init,['Argument__1']}},{pid,<0.19.0>},{registered_name,[]},{error_info,{exit,{error,badarg},[{gen_server,init_it,6},{proc_lib,init_p_do_apply,3}]}},{ancestors,[net_sup,kernel_sup,<0.9.0>]},{messages,[]},{links,[#Port<0.99>,<0.16.0>]},{dictionary,[{longnames,false}]},{trap_exit,true},{status,running},{heap_size,377},{stack_size,24},{reductions,464}],[]]}
{error_logger,{{2013,7,2},{6,58,32}},supervisor_report,[{supervisor,{local,net_sup}},{errorContext,start_error},{reason,{'EXIT',nodistribution}},{offender,[{pid,undefined},{name,net_kernel},{mfargs,{net_kernel,start_link,[[ejabberd,shortnames]]}},{restart_type,permanent},{shutdown,2000},{child_type,worker}]}]}
{error_logger,{{2013,7,2},{6,58,32}},supervisor_report,[{supervisor,{local,kernel_sup}},{errorContext,start_error},{reason,shutdown},{offender,[{pid,undefined},{name,net_sup},{mfargs,{erl_distribution,start_link,[]}},{restart_type,permanent},{shutdown,infinity},{child_type,supervisor}]}]}
{error_logger,{{2013,7,2},{6,58,32}},std_info,[{application,kernel},{exited,{shutdown,{kernel,start,[normal,[]]}}},{type,permanent}]}
{"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{shutdown,{kernel,start,[normal,[]]}}}"}

Crash dump was written to: /var/log/ejabberd/erl_crash.dump
Kernel pid terminated (application_controller) ({application_start_failure,kernel,{shutdown,{kernel,start,[normal,[]]}}})
```

Somehow I can still connect to the Archipel GUI. This is not a fresh install, this is an updated system (I think I should've just stayed with the old version...). 

I need to have this fixed ASAP, any help is really appreciated, thanks.

**Comment by orbitalmute** [comment]
I have same problem. After adding hypervisor i see only chat windows. Logs file is clean. What does it mean?

**Comment by CyrilPeponnet** [comment]
Mean that ether you miscondigured something or you are using a buggy ejabberd release. 

Try to get vCard from command line like above to see where your problem stand.
